server:
  port: 9999

spring:
  profiles:
    active: prod

  application: gateway
  main:
    web-application-type: reactive

  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
              - OPTIONS

      routes:
        ####### Api #######
        - id: api
          uri: http://localhost:9001
          predicates:
            - Path=/api/members/sign-up,/api/members/sign-in,/api/posts/{keyword}/search
        - id: api
          uri: http://localhost:9001
          predicates:
            - Path=/api/**
          filters:
            - JwtAuthenticationFilter

  redis:
    mode: standalone
    nodes: localhost:26379

  output:
    ansi:
      enabled: always

jwt:
  secret-key: kotlinMultiModuleTemplateBackendJsonWebToken
